# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/NUS/ee2026/MyWork/lab_1/lab_1.cache/wt [current_project]
set_property parent.project_path D:/NUS/ee2026/MyWork/lab_1/lab_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/NUS/ee2026/MyWork/lab_1/lab_1.srcs/sources_1/new/lab_1.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/NUS/ee2026/MyWork/lab_1/lab_1.srcs/constrs_1/new/lab_1_constraints.xdc
set_property used_in_implementation false [get_files D:/NUS/ee2026/MyWork/lab_1/lab_1.srcs/constrs_1/new/lab_1_constraints.xdc]


synth_design -top lab_1 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab_1.dcp

catch { report_utilization -file lab_1_utilization_synth.rpt -pb lab_1_utilization_synth.pb }
