# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/NUS/ee2026/MyWork/lab2/lab2.cache/wt [current_project]
set_property parent.project_path D:/NUS/ee2026/MyWork/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/NUS/ee2026/MyWork/lab2/lab2.srcs/sources_1/new/lab2.v
  D:/NUS/ee2026/MyWork/lab2/lab2.srcs/sources_1/new/4bitadder.v
  D:/NUS/ee2026/MyWork/lab2/lab2.srcs/sources_1/new/1complement.v
  D:/NUS/ee2026/MyWork/lab2/lab2.srcs/sources_1/new/4bitsubtractor.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/NUS/ee2026/MyWork/lab2/lab2.srcs/constrs_1/new/4bitsubtractorcontrains.xdc
set_property used_in_implementation false [get_files D:/NUS/ee2026/MyWork/lab2/lab2.srcs/constrs_1/new/4bitsubtractorcontrains.xdc]


synth_design -top fourBitSubtractor -part xc7a35tcpg236-1


write_checkpoint -force -noxdef fourBitSubtractor.dcp

catch { report_utilization -file fourBitSubtractor_utilization_synth.rpt -pb fourBitSubtractor_utilization_synth.pb }
